security:
  oauth2:
    client:
      clientId: 1993571567628934
      clientSecret: 63836562994d56e8eb7088a79795b455
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me